services:
  - type: web
    name: foodexpress
    runtime: python
    plan: free
    region: singapore
    repo: https://github.com/Poonghuzhali/FoodExpress
    branch: master
    buildCommand: bash build.sh
    startCommand: gunicorn fooddelivery.wsgi:application --bind 0.0.0.0:$PORT
    healthCheckPath: /health/
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.3"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false
